---
version: 2
jobs:
  node-8: &test-build
    docker:
      - image: node:8
    working_directory: /cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{ .Branch }}-
            - v0-yarn-master-
      - run: yarn
      - run: yarn test --coverage
      - save_cache:
          key: v0-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - /cli/node_modules
            - /usr/local/share/.cache/yarn
  node-latest:
    <<: *test-build
    docker:
      - image: node:latest

workflows:
  version: 2
  test:
    jobs:
      - node-8
      - node-latest
